# Generated by Django 5.1.7 on 2025-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowControlerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "growcontroler_name",
                    models.CharField(
                        default="growcontroler",
                        help_text="Name for accessing GrowControler in local network (e.g. growcontroler.local)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GrowControler Settings",
            },
        ),
    ]
