# Generated by Django 5.1.7 on 2025-03-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0002_growcontrolersettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GrowControlerSettings",
        ),
    ]
