# Generated by Django 5.1.7 on 2025-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0003_delete_growcontrolersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=255)),
                ("installation_date", models.DateTimeField(auto_now_add=True)),
                ("is_on", models.BooleanField(default=False)),
                ("last_changed", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_type", models.CharField(max_length=255)),
                ("sensor_name", models.CharField(max_length=255)),
                ("installation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
