# Generated by Django 5.1.7 on 2025-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0006_remove_sensordata_humidity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="threshold",
            field=models.FloatField(default=0.0),
        ),
    ]
