# Generated by Django 5.1.7 on 2025-03-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0007_sensordata_threshold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensordata",
            options={"get_latest_by": "timestamp"},
        ),
    ]
