# Generated by Django 5.1.7 on 2025-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinterface", "0008_alter_sensordata_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="threshold",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="thresholds",
            field=models.JSONField(default=dict),
        ),
    ]
